/**
 * @packageDocumentation
 * @module api.functional.res
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";

import type { CreateResourceDto } from "../../structures/CreateResourceDto";
import type { ResourceDto } from "../../structures/ResourceDto";

export * as logs from "./logs/index";
export * as stat from "./stat/index";

/**
 * @controller ResourcesController.create
 * @path POST /res
 * @accessor api.functional.res.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  body: create.Body,
): Promise<create.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...create.METADATA,
      template: create.METADATA.path,
      path: create.path(),
    },
    body,
  );
}
export namespace create {
  export type Body = CreateResourceDto;
  export type Output = ResourceDto;

  export const METADATA = {
    method: "POST",
    path: "/res",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/res";
}

/**
 * @controller ResourcesController.findAll
 * @path GET /res
 * @accessor api.functional.res.findAll
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function findAll(
  connection: IConnection,
): Promise<findAll.Output> {
  return PlainFetcher.fetch(connection, {
    ...findAll.METADATA,
    template: findAll.METADATA.path,
    path: findAll.path(),
  });
}
export namespace findAll {
  export type Output = ResourceDto[];

  export const METADATA = {
    method: "GET",
    path: "/res",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/res";
}

/**
 * @controller ResourcesController.findOne
 * @path GET /res/:slug
 * @accessor api.functional.res.findOne
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function findOne(
  connection: IConnection,
  slug: string,
): Promise<findOne.Output> {
  return PlainFetcher.fetch(connection, {
    ...findOne.METADATA,
    template: findOne.METADATA.path,
    path: findOne.path(slug),
  });
}
export namespace findOne {
  export type Output = ResourceDto;

  export const METADATA = {
    method: "GET",
    path: "/res/:slug",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (slug: string) =>
    `/res/${encodeURIComponent(slug?.toString() ?? "null")}`;
}

/**
 * @controller ResourcesController.update
 * @path PATCH /res/:slug
 * @accessor api.functional.res.update
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
  connection: IConnection,
  name: string,
): Promise<update.Output> {
  return PlainFetcher.fetch(connection, {
    ...update.METADATA,
    template: update.METADATA.path,
    path: update.path(name),
  });
}
export namespace update {
  export type Output = string;

  export const METADATA = {
    method: "PATCH",
    path: "/res/:slug",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (name: string) =>
    `/res/${encodeURIComponent(name?.toString() ?? "null")}`;
}

/**
 * @controller ResourcesController.remove
 * @path DELETE /res/:slug
 * @accessor api.functional.res.remove
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function remove(
  connection: IConnection,
  slug: string,
): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ...remove.METADATA,
    template: remove.METADATA.path,
    path: remove.path(slug),
  });
}
export namespace remove {
  export const METADATA = {
    method: "DELETE",
    path: "/res/:slug",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (slug: string) =>
    `/res/${encodeURIComponent(slug?.toString() ?? "null")}`;
}
