/**
 * @packageDocumentation
 * @module api.functional.res.logs
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";

import type { IncomingLogDto } from "../../../structures/IncomingLogDto";

/**
 * @controller LogsController.create
 * @path POST /res/:slug/logs
 * @accessor api.functional.res.logs.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  slug: string,
  body: create.Body,
): Promise<void> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...create.METADATA,
      template: create.METADATA.path,
      path: create.path(slug),
    },
    body,
  );
}
export namespace create {
  export type Body = IncomingLogDto;

  export const METADATA = {
    method: "POST",
    path: "/res/:slug/logs",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = (slug: string) =>
    `/res/${encodeURIComponent(slug?.toString() ?? "null")}/logs`;
}

/**
 * @controller LogsController.findAll
 * @path GET /res/:slug/logs
 * @accessor api.functional.res.logs.findAll
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function findAll(
  connection: IConnection,
  slug: string,
): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ...findAll.METADATA,
    template: findAll.METADATA.path,
    path: findAll.path(slug),
  });
}
export namespace findAll {
  export const METADATA = {
    method: "GET",
    path: "/res/:slug/logs",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (slug: string) =>
    `/res/${encodeURIComponent(slug?.toString() ?? "null")}/logs`;
}

/**
 * @controller LogsController.findOne
 * @path GET /res/:slug/logs/:id
 * @accessor api.functional.res.logs.findOne
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function findOne(
  connection: IConnection,
  slug: string,
  id: number,
): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ...findOne.METADATA,
    template: findOne.METADATA.path,
    path: findOne.path(slug, id),
  });
}
export namespace findOne {
  export const METADATA = {
    method: "GET",
    path: "/res/:slug/logs/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (slug: string, id: number) =>
    `/res/${encodeURIComponent(slug?.toString() ?? "null")}/logs/${encodeURIComponent(id?.toString() ?? "null")}`;
}
