/**
 * @packageDocumentation
 * @module api.functional.res.stat
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
export * as logs from "./logs/index";
