/**
 * @packageDocumentation
 * @module api.functional.res.stat.logs
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";

import type { LogStatDto } from "../../../../structures/LogStatDto";

/**
 * @controller LogsController.getLogsStat
 * @path GET /res/:slug/stat/logs
 * @accessor api.functional.res.stat.logs.getLogsStat
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getLogsStat(
  connection: IConnection,
  slug: string,
): Promise<getLogsStat.Output> {
  return PlainFetcher.fetch(connection, {
    ...getLogsStat.METADATA,
    template: getLogsStat.METADATA.path,
    path: getLogsStat.path(slug),
  });
}
export namespace getLogsStat {
  export type Output = LogStatDto;

  export const METADATA = {
    method: "GET",
    path: "/res/:slug/stat/logs",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (slug: string) =>
    `/res/${encodeURIComponent(slug?.toString() ?? "null")}/stat/logs`;
}
